const ADMIN_PREFIX = '/admin';
export const ROUTES = {
    LOGIN: `${ADMIN_PREFIX}/login`,
    FORGOT_PASSWORD: `${ADMIN_PREFIX}/forgot-password`,
    RESET_PASSWORD: "/reset-password",
    DASHBOARD: `${ADMIN_PREFIX}`,
    PROFILE: `${ADMIN_PREFIX}/profile`,
    USERS: `${ADMIN_PREFIX}/users`,
    ROLES: `${ADMIN_PREFIX}/roles`,
    PERMISSIONS: `${ADMIN_PREFIX}/permissions`,
    CATEGORIES: `${ADMIN_PREFIX}/categories`,
    PRODUCTS: `${ADMIN_PREFIX}/products`,
    PRODUCT_VARIANTS: `${ADMIN_PREFIX}/product-variants`,
    UNITS: `${ADMIN_PREFIX}/units`,
    INVENTORY: `${ADMIN_PREFIX}/inventory`,
    TAX_CLASSES: `${ADMIN_PREFIX}/tax-classes`,
    TAX_RATES: `${ADMIN_PREFIX}/tax-rates`,
    ATTRIBUTES: `${ADMIN_PREFIX}/attributes`,
    ORDERS: `${ADMIN_PREFIX}/orders`,
    COUPONS: `${ADMIN_PREFIX}/coupons`,
    RETURNS: `${ADMIN_PREFIX}/returns`,
    SHIPMENTS: `${ADMIN_PREFIX}/shipments`,
    INVOICES: `${ADMIN_PREFIX}/invoices`,
    PAYMENTS: `${ADMIN_PREFIX}/payments`,
    CARTS: `${ADMIN_PREFIX}/carts`,
    WISHLISTS: `${ADMIN_PREFIX}/wishlists`,
    PURCHASE_ORDERS: `${ADMIN_PREFIX}/purchase-orders`,
    GOODS_RECEIPTS: `${ADMIN_PREFIX}/goods-receipts`,
    PURCHASE_INVOICES: `${ADMIN_PREFIX}/purchase-invoices`,
    PURCHASE_PAYMENTS: `${ADMIN_PREFIX}/purchase-payments`,
    PURCHASE_RETURNS: `${ADMIN_PREFIX}/purchase-returns`,
        CUSTOMERS: `${ADMIN_PREFIX}/customers`,
    ADDRESSES: `${ADMIN_PREFIX}/addresses`,
    SUPPLIERS: `${ADMIN_PREFIX}/suppliers`,
    SHIPPING_ZONES: `${ADMIN_PREFIX}/shipping/zones`,
    SHIPPING_METHODS: `${ADMIN_PREFIX}/shipping/methods`,
    SHIPPING_RATES: `${ADMIN_PREFIX}/shipping/rates`,
} as const;