export const ROUTES = {
    LOGIN: "/login",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    DASHBOARD: "/",
    PROFILE: "/profile",
    USERS: "/users",
    ROLES: "/roles",
    PERMISSIONS: "/permissions",
    CATEGORIES: "/categories",
    PRODUCTS: "/products",
    PRODUCT_VARIANTS: "/product-variants",
    UNITS: "/units",
    INVENTORY: "/inventory",
} as const;